/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddAccountWindow.java
 *
 * Created on 21-feb-2009, 1:10:27
 */
package com.googlecode.pennybank.swing.view.account;

import com.googlecode.pennybank.App;
import com.googlecode.pennybank.model.account.entity.Account;
import com.googlecode.pennybank.model.accountfacade.delegate.AccountFacadeDelegate;
import com.googlecode.pennybank.model.accountfacade.delegate.AccountFacadeDelegateFactory;
import com.googlecode.pennybank.model.util.exceptions.InstanceNotFoundException;
import com.googlecode.pennybank.model.util.exceptions.InternalErrorException;
import com.googlecode.pennybank.swing.view.main.MainWindow;
import com.googlecode.pennybank.swing.view.util.IconManager;
import com.googlecode.pennybank.swing.view.util.MessageManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 * JDialog which allows the user to create a new account
 *
 * @author spenap
 */
public class AddAccountWindow extends javax.swing.JDialog {

    /**
     * Creates a new AddAccountWindow with the specified parameters
     *
     * @param parent The parent JFrame
     * @param modal Boolean value indicating whether this is modal or not
     */
    public AddAccountWindow(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        accountIcon = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        fieldsPanel = new javax.swing.JPanel();
        accountNameLabel = new javax.swing.JLabel();
        accountNameTextField = new javax.swing.JTextField();
        balanceLabel = new javax.swing.JLabel();
        balanceTextField = new javax.swing.JTextField();

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(MessageManager.getMessage("AddAccountWindow.Title"));
        setResizable(false);

        accountIcon.setIcon(IconManager.getIcon("toolbar_add_account"));
        accountIcon.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        getContentPane().add(accountIcon, java.awt.BorderLayout.WEST);

        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText(MessageManager.getMessage("okButton"));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(okButton);

        cancelButton.setText(MessageManager.getMessage("cancelButton"));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(cancelButton);

        getContentPane().add(buttonsPanel, java.awt.BorderLayout.PAGE_END);

        fieldsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        fieldsPanel.setLayout(new java.awt.GridLayout(2, 2, 2, 0));

        accountNameLabel.setText(MessageManager.getMessage("AccountWindow.AccountName"));
        fieldsPanel.add(accountNameLabel);

        accountNameTextField.setMinimumSize(new java.awt.Dimension(100, 28));
        accountNameTextField.setPreferredSize(new java.awt.Dimension(30, 28));
        fieldsPanel.add(accountNameTextField);

        balanceLabel.setText(MessageManager.getMessage("AccountWindow.Balance"));
        fieldsPanel.add(balanceLabel);

        balanceTextField.setMinimumSize(new java.awt.Dimension(100, 28));
        balanceTextField.setPreferredSize(new java.awt.Dimension(30, 28));
        fieldsPanel.add(balanceTextField);

        getContentPane().add(fieldsPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        Account theAccount =
                new Account(App.getCurrentUser(), Double.parseDouble(balanceTextField.
                getText()), accountNameTextField.getText());
        try {

            AccountFacadeDelegate accountFacade =
                    AccountFacadeDelegateFactory.getDelegate();
            theAccount = accountFacade.createAccount(theAccount);
        } catch (InstanceNotFoundException ex) {
            Logger.getLogger(AddAccountWindow.class.getName()).
                    log(Level.SEVERE, null, ex);
        } catch (InternalErrorException ex) {
            Logger.getLogger(AddAccountWindow.class.getName()).
                    log(Level.SEVERE, null, ex);
        }
        MainWindow.getInstance().getNavigationPanel().addAccount(theAccount);
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AddAccountWindow dialog =
                        new AddAccountWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountIcon;
    private javax.swing.JLabel accountNameLabel;
    private javax.swing.JTextField accountNameTextField;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JTextField balanceTextField;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel fieldsPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
