/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Created on 21-feb-2009, 13:50:47
 */
package com.googlecode.pennybank.swing.view.main;

import com.googlecode.pennybank.model.accountfacade.vo.AccountOperationInfo;
import com.googlecode.pennybank.model.util.vo.Block;
import com.googlecode.pennybank.swing.view.util.MessageManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 * JPanel showing the Main Content for the application
 * 
 * @author spenap
 */
public class MainContentPanel extends javax.swing.JPanel {

    /** 
     * Creates a new Main Content Panel
     */
    public MainContentPanel() {
        initComponents();
    }

    private TableModel getAccountOperationsTableModel() {

        DefaultTableModel accountOperationsTableModel = new DefaultTableModel();
        accountOperationsTableModel.addColumn(MessageManager.getMessage("AccountOperationTable.Type"));
        accountOperationsTableModel.addColumn(MessageManager.getMessage("AccountOperationTable.Amount"));
        accountOperationsTableModel.addColumn(MessageManager.getMessage("AccountOperationTable.Date"));
        accountOperationsTableModel.addColumn(MessageManager.getMessage("AccountOperationTable.Comment"));
        accountOperationsTableModel.addColumn(MessageManager.getMessage("AccountOperationTable.Categories"));

        return accountOperationsTableModel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountOperationsScrollPane = new javax.swing.JScrollPane();
        accountOperationsTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        accountOperationsTable.setModel(getAccountOperationsTableModel());
        accountOperationsScrollPane.setViewportView(accountOperationsTable);

        add(accountOperationsScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public void setAccountOperations(Block<AccountOperationInfo> accountOperationBlocks) {

        DefaultTableModel tableModel =
                (DefaultTableModel) accountOperationsTable.getModel();

        tableModel.setRowCount(accountOperationBlocks.getContents().size());

        for (int i = 0; i < accountOperationBlocks.getContents().
                size(); i++) {
            AccountOperationInfo accountOperationInfo = accountOperationBlocks.
                    getContents().
                    get(i);
            // Type
            accountOperationsTable.setValueAt(accountOperationInfo.getType(), i, 0);

            // Ammount
            accountOperationsTable.setValueAt(accountOperationInfo.getAmount(), i, 1);

            // Date
            accountOperationsTable.setValueAt(accountOperationInfo.getDate().
                    getTime().
                    toString(), i, 2);

            // Comment
            accountOperationsTable.setValueAt(accountOperationInfo.getComment(), i, 3);

            // Categories
            accountOperationsTable.setValueAt(accountOperationInfo.getCategories(), i, 4);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane accountOperationsScrollPane;
    private javax.swing.JTable accountOperationsTable;
    // End of variables declaration//GEN-END:variables
}
