/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddProfileWindow.java
 *
 * Created on 21-feb-2009, 13:01:53
 */
package com.googlecode.pennybank.swing.view.profile;

import com.googlecode.pennybank.model.user.entity.User;
import com.googlecode.pennybank.model.userfacade.delegate.UserFacadeDelegate;
import com.googlecode.pennybank.model.userfacade.delegate.UserFacadeDelegateFactory;
import com.googlecode.pennybank.model.util.exceptions.InternalErrorException;
import com.googlecode.pennybank.swing.view.util.IconManager;
import com.googlecode.pennybank.swing.view.util.MessageManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 * JDialog allowing the user to create a new profile
 * 
 * @author spenap
 */
public class AddProfileWindow extends javax.swing.JDialog {

    /** 
     * Creates a new AddProfileWindow with the specified parameters
     * 
     * @param parent The parent JFrame
     * @param modal Boolean value telling whether this JDialog is modal or not
     */
    public AddProfileWindow(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        profileIcon = new javax.swing.JLabel();
        fieldsPanel = new javax.swing.JPanel();
        profileNameLabel = new javax.swing.JLabel();
        profileNameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(MessageManager.getMessage("AddProfileWindow.Title"));
        setResizable(false);

        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText(MessageManager.getMessage("okButton"));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(okButton);

        cancelButton.setText(MessageManager.getMessage("cancelButton"));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(cancelButton);

        getContentPane().add(buttonsPanel, java.awt.BorderLayout.PAGE_END);

        profileIcon.setIcon(IconManager.getIcon("toolbar_add_user"));
        profileIcon.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        getContentPane().add(profileIcon, java.awt.BorderLayout.LINE_START);

        fieldsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        fieldsPanel.setLayout(new java.awt.GridLayout(1, 2, 0, 1));

        profileNameLabel.setText(MessageManager.getMessage("ProfileWindow.ProfileName"));
        fieldsPanel.add(profileNameLabel);
        fieldsPanel.add(profileNameTextField);

        getContentPane().add(fieldsPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        User user = new User(profileNameTextField.getText());
        try {
            UserFacadeDelegate userFacade =
                    UserFacadeDelegateFactory.getDelegate();
            userFacade.createUser(user);
            this.dispose();

        } catch (InternalErrorException ex) {
            Logger.getLogger(AddProfileWindow.class.getName()).
                    log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AddProfileWindow dialog =
                        new AddProfileWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel fieldsPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JLabel profileNameLabel;
    private javax.swing.JTextField profileNameTextField;
    // End of variables declaration//GEN-END:variables
}
